config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'signup' => 'users#new'
  post   'login'   => 'sessions#create'

	post '/share' => 'cards#share'
	delete 'logout'  => 'sessions#destroy'
	
  resources :users
  resources :cards
  root 'sessions#new'
  
end

app/models/card.rb
class Card < ActiveRecord::Base

	belongs_to :user
	has_many :usercards

	validates :month, length: { maximum: 2 }
	validates :day, length: { maximum: 2 }

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :cards, through: :usercards
	has_many :usercards

	validates :phone, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
	
end

app/models/usercard.rb
class Usercard < ActiveRecord::Base
	belongs_to :user
	belongs_to :card
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include ApplicationHelper



  def current_user
    if session[:user_id]       
			@current_user = User.find(session[:user_id])    
		end 
 end
 
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def new
    @user = User.find(params[:user_id])
  	@card = Card.new
  end

  def create
    puts "SAVING"
  	@user = User.find(params[:user_id])
		@card = @user.cards.create(card_params)
    @card = Card.create(card_params)
    if @card.save
      redirect_to @user
    else
      puts "TEST"
      redirect_to root_path
    end
  end

  def share
    user = User.find(params[:user_id])
    card = Card.find(params[:card_id])
    if user.cards << card
      puts "ADDED THIS"
      respond_to do |format|
        format.js
      end
    else
      redirect_to root_path
    end
  end

  private

  def card_params
      params.require(:card).permit(:account, :type, :month, :year)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	include SessionsHelper

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
    if @user.save
      log_in @user
    	flash[:success] = "Welcome to AMAZING!"
      redirect_to @user
    else
      render 'new'
    end
	end

	def show
		@user = User.find(params[:id])
	end

	def index
		@users = User.all
		@user = User.find(params[:user_id])
		@card = Card.find(params[:card_id])
	end


  private

  def user_params
      params.require(:user).permit(:first, :last, :phone, :balance, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/card_helper.rb
module CardHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	# defines the current user from the presence of a session
	def current_user
    if session[:user_id]       
			@current_user = User.find(session[:user_id])    
		end 
 	end

	# Log in user
	def log_in(user)
    session[:user_id] = user.id
  end

  # this is test if a current user exists - as a way of removing the menu on the root_path
  def logged_in?
    !current_user.nil?
  end
 
 	# this is for the sign out link
  def log_out
    session.delete(:user_id)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/new.html.erb
<h1>New Card Page</h1>
<h4><%= @user.phone %></h4>


<div class="box" id="card_info">
	<%= form_for @card, :url => {action: :create, user_id: @user.id} do |f| %>
        <%= f.text_field :account, :placeholder => "Account Number" %>
        <br>
        <%= f.text_field :card_type, :placeholder => "Type of Card" %>
        <br>
        <%= f.text_field :month, :placeholder => "Month(1-12)" %>
        <br>
        <%= f.text_field :year, :placeholder => "Year" %>
        <br>
        <%= f.submit "Create" %>
    <% end %>
</div>

<%= link_to "BACK", @user %>

app/views/cards/share.js.erb
$(document).ready(function() {
	// alert("Hi");
	$('#share_message').text("This card has been shared");
});

app/views/layouts/_footer.html.erb
<footer class="col-sm-12">The Amazing Wallet App by vivek gahunia</footer>

app/views/layouts/_header.html.erb
<header class="col-sm-12">
	<h1>The Amazing Wallet App</h1>
	<% if logged_in? %>
		<ul class="nav col-sm-12">
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Log out", logout_path, method: "delete" %></li>
		</ul>
	<% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wallet</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Comfortaa' rel='stylesheet' type='text/css'>
  </head>

  <body class="container-fluid">
  	
  	<%= render 'layouts/header' %>
  	<% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

  	<%= yield %>

  	<%= render 'layouts/footer' %>

  </body>
  
</html>

app/views/users/index.html.erb
<div class="row" id="index_heading">
	<div class="col-lg-offset-4 col-lg-4">
		<h3><span class="bold"><%= @user.first %></span>, who would you like to share your card with?</h3> 
	</div>
</div>

<div class="row">
	<div class="col-lg-offset-4 col-lg-4">
		<ul>
			<% @users.each do |user| %>
				<%= link_to "#{user.first} #{user.last}", share_path(user_id: user.id, card_id: @card.id), method: :post, remote: true %>
				<br>
				<div id="share_message"><div>
			<% end %>
			<br>
		</ul>

		<%= link_to "BACK", @user %>
	</div>
</div>

app/views/users/new.html.erb
	<div class="signin col-sm-12">
    <div class="empty col-sm-2"></div>
    <div id="signup_form" class="col-sm-4">
      <h3>Sign Up Form</h3>
  	 <%= form_for User.new do |f| %>
      <%= f.text_field :first, :placeholder => "First Name" %>
      <br>
      <%= f.text_field :last, :placeholder => "Last Name" %>
      <br>
      <%= f.text_field :phone, :placeholder => "Phone" %>
      <br>
      <%= f.text_field :balance, :placeholder => "Balance" %>
      <br>
      <%= f.text_field :email, :placeholder => "Email" %>
      <br>
      <%= f.submit "Get Started!", class: "button" %>
     <% end %>
    </div>
    <div class="col-sm-4" id="signup_plug">
      <p>Do you even realize how AMAZING the Amazing Wallet App is?</p>
      <p>(You probably don't.)</p>
      <p>But you're about to find out!</p>
    </div>
    <div class="empty col-sm-2"></div>
  </div>


  <!-- Display error messages if the user has any -->

  <% if @user.errors.full_messages.any? %>
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
      	<li><%= error_message%></li> <br />
      <% end %>
    </ul>
  <% end %>

app/views/users/show.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		
		<div id="user_info">
			<div class="row">
				<div class="col-md-4 col-md-offset-4">
					<h2><%= @user.first %> <%= @user.last %></h2>
				</div>
			</div>
			<div class="row">
				<div class="col-md-6" id="user_info_left">
					<h4><span class="info_label">Phone:</span></h4>
					<h4><span class="info_label">Email:</span></h4>
					<h4><span class="info_label">Current Balance:</span></h4>
					<h4><span class="info_label">ID:</span></h4>
				</div>
				<div class="col-md-6" id="user_info_right">
					<h4><%= @user.phone %></h4>
					<h4><%= @user.email %></h4>
					<h4><%= @user.balance %></h4>
					<h4><%= @user.id %></h4>
				</div>
			</div>
		</div>

		<div id="card_info">
			<div class="row">
				<div class="col-md-4 col-md-offset-4">
					<h2>Your card(s):</h2>
				</div>
			</div>
			<% if @user.cards.any? %>
				<% @user.cards.each do |card| %>
					<%= card.account %>
					<%= card.card_type %><br>
					<%= card.month %><br>
					<%= card.year %><br>
					<%= link_to "Share this card", users_path({user_id: @user.id, card_id: card.id}) %>
					<br>
				<% end %>
			<% else %>
					<h3>You currently have no cards attached to your account.</h3>
			<% end %>
			<br>
			<%= link_to "Add a card", new_card_path({user_id: @user.id}) %>
		</div>
	</div>
</div>